export const clients = [
  {
    id: 'client001',
    name: 'Synergy Home',
    industry: 'HVAC',
    location: 'Charlotte, NC',
    status: 'active',
    monthlyBudget: 20000,
  },
  {
    id: 'client002',
    name: 'Peak Roofing Co.',
    industry: 'Roofing',
    location: 'Atlanta, GA',
    status: 'active',
    monthlyBudget: 15000,
  },
  {
    id: 'client003',
    name: 'Greenway Solar',
    industry: 'Solar',
    location: 'Tampa, FL',
    status: 'active',
    monthlyBudget: 25000,
  },
]

export const dashboardData = {
  client001: {
    adSpend: 18750,
    leads: 142,
    appointmentsSet: 89,
    appointmentsCompleted: 67,
    sales: 23,
    revenue: 287500,
    costPerLead: 132,
    apptSetRate: 62.7,
    apptCompletedRate: 75.3,
    closeRate: 34.3,
    revenuePerLead: 2024,
    costPerSale: 815,
    chartLabels: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
    chartLeads: [18, 26, 22, 35, 42, 38, 45],
  },
  client002: {
    adSpend: 12400,
    leads: 87,
    appointmentsSet: 52,
    appointmentsCompleted: 41,
    sales: 14,
    revenue: 168000,
    costPerLead: 143,
    apptSetRate: 59.8,
    apptCompletedRate: 78.8,
    closeRate: 34.1,
    revenuePerLead: 1931,
    costPerSale: 886,
    chartLabels: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
    chartLeads: [10, 14, 12, 18, 22, 21, 25],
  },
  client003: {
    adSpend: 22100,
    leads: 198,
    appointmentsSet: 124,
    appointmentsCompleted: 98,
    sales: 31,
    revenue: 465000,
    costPerLead: 112,
    apptSetRate: 62.6,
    apptCompletedRate: 79.0,
    closeRate: 31.6,
    revenuePerLead: 2348,
    costPerSale: 713,
    chartLabels: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
    chartLeads: [22, 30, 28, 40, 52, 48, 58],
  },
}

// YouTube Ads — campaign-level table data (mirrors Google Ads structure + CH attribution columns)
export const youtubeData = {
  client001: {
    campaigns: [
      {
        name: 'HVAC — Repair vs Replace [YT In-Stream]',
        status: 'enabled',
        budget: 40,
        cost: 168,
        clicks: 57,
        cpc: 2.95,
        conv: 0,
        costPerConv: 0,
        chConv: 3,
        chCostPerConv: 56.0,
      },
      {
        name: 'HVAC — Summer AC Promo [YT In-Feed]',
        status: 'enabled',
        budget: 33,
        cost: 0,
        clicks: 0,
        cpc: 0,
        conv: 0,
        costPerConv: 0,
        chConv: 0,
        chCostPerConv: 0,
      },
      {
        name: 'HVAC — Free Second Opinion [YT Bumper]',
        status: 'paused',
        budget: 33,
        cost: 0,
        clicks: 0,
        cpc: 0,
        conv: 0,
        costPerConv: 0,
        chConv: 0,
        chCostPerConv: 0,
      },
      {
        name: 'HVAC — Brand Awareness [YT Skippable]',
        status: 'enabled',
        budget: 33,
        cost: 0,
        clicks: 0,
        cpc: 0,
        conv: 0,
        costPerConv: 0,
        chConv: 0,
        chCostPerConv: 0,
      },
    ],
  },
  client002: {
    campaigns: [
      {
        name: 'Roofing — Storm Damage [YT In-Stream]',
        status: 'enabled',
        budget: 35,
        cost: 142,
        clicks: 48,
        cpc: 2.96,
        conv: 1,
        costPerConv: 142,
        chConv: 2,
        chCostPerConv: 71.0,
      },
      {
        name: 'Roofing — Free Inspection [YT In-Feed]',
        status: 'enabled',
        budget: 28,
        cost: 89,
        clicks: 31,
        cpc: 2.87,
        conv: 0,
        costPerConv: 0,
        chConv: 1,
        chCostPerConv: 89.0,
      },
      {
        name: 'Roofing — Testimonials [YT Skippable]',
        status: 'paused',
        budget: 20,
        cost: 0,
        clicks: 0,
        cpc: 0,
        conv: 0,
        costPerConv: 0,
        chConv: 0,
        chCostPerConv: 0,
      },
    ],
  },
  client003: {
    campaigns: [
      {
        name: 'Solar — Is It Worth It? [YT In-Stream]',
        status: 'enabled',
        budget: 50,
        cost: 412,
        clicks: 139,
        cpc: 2.96,
        conv: 3,
        costPerConv: 137.33,
        chConv: 7,
        chCostPerConv: 58.86,
      },
      {
        name: 'Solar — Savings Calculator [YT In-Feed]',
        status: 'enabled',
        budget: 45,
        cost: 318,
        clicks: 104,
        cpc: 3.06,
        conv: 2,
        costPerConv: 159,
        chConv: 5,
        chCostPerConv: 63.6,
      },
      {
        name: 'Solar — Free Quote [YT Bumper]',
        status: 'enabled',
        budget: 30,
        cost: 198,
        clicks: 67,
        cpc: 2.96,
        conv: 1,
        costPerConv: 198,
        chConv: 3,
        chCostPerConv: 66.0,
      },
      {
        name: 'Solar — Brand [YT Skippable]',
        status: 'paused',
        budget: 25,
        cost: 0,
        clicks: 0,
        cpc: 0,
        conv: 0,
        costPerConv: 0,
        chConv: 0,
        chCostPerConv: 0,
      },
    ],
  },
}
