#!/usr/bin/env node
/**
 * Dump the live Supabase public schema into the repo so it's version-controlled
 * and readable (by humans and AI assistants) without screenshots or guessing.
 *
 *   npm run db:schema
 *
 * Writes:
 *   db/schema.json  — machine-readable (tables → columns → type/nullable/default/keys)
 *   db/schema.md    — human/AI-readable catalog
 *
 * Uses the credentials already in .env.local (NEXT_PUBLIC_SUPABASE_URL +
 * SUPABASE_SERVICE_ROLE_KEY). No psql / pg_dump / supabase CLI required.
 *
 * Two introspection methods, tried in order:
 *   1. RPC `schema_catalog()` — full fidelity (exact PG types + defaults).
 *      Install it once with sql/2026-06-25_schema_catalog_rpc.sql (optional).
 *   2. PostgREST OpenAPI (/rest/v1/) — works with ZERO database setup.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// ── load .env.local (tiny parser, no dotenv dependency) ──
function loadEnv() {
  const env = {}
  try {
    const raw = readFileSync(resolve(ROOT, '.env.local'), 'utf8')
    for (const line of raw.split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
      if (!m) continue
      let v = m[2].trim()
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1)
      env[m[1]] = v
    }
  } catch { /* fall through to process.env */ }
  return { ...env, ...process.env }
}

const env = loadEnv()
const URL = env.NEXT_PUBLIC_SUPABASE_URL
const KEY = env.SUPABASE_SERVICE_ROLE_KEY
if (!URL || !KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY (checked .env.local and process.env).')
  process.exit(1)
}
const headers = { apikey: KEY, Authorization: `Bearer ${KEY}` }

// ── method 1: high-fidelity RPC ──
async function viaRpc() {
  const res = await fetch(`${URL}/rest/v1/rpc/schema_catalog`, {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: '{}',
  })
  if (!res.ok) return null
  const rows = await res.json()
  if (!Array.isArray(rows) || !rows.length) return null
  const tables = {}
  for (const r of rows) {
    const t = (tables[r.table_name] ||= { name: r.table_name, columns: [] })
    t.columns.push({
      name: r.column_name,
      type: r.data_type,
      nullable: r.is_nullable === 'YES' || r.is_nullable === true,
      default: r.column_default ?? null,
      pk: !!r.is_primary_key,
      fk: r.foreign_key || null,
    })
  }
  return { method: 'rpc:schema_catalog', tables: Object.values(tables).sort(byName) }
}

// ── method 2: zero-setup PostgREST OpenAPI ──
async function viaOpenApi() {
  const res = await fetch(`${URL}/rest/v1/`, { headers })
  if (!res.ok) throw new Error(`OpenAPI introspection failed: ${res.status} ${await res.text()}`)
  const spec = await res.json()
  const defs = spec.definitions || {}
  const tables = []
  for (const [name, def] of Object.entries(defs)) {
    const required = new Set(def.required || [])
    const columns = Object.entries(def.properties || {}).map(([col, p]) => {
      const desc = p.description || ''
      const pk = /Primary Key/i.test(desc)
      const fkMatch = desc.match(/Foreign Key to `([^`]+)`/i)
      return {
        name: col,
        type: p.format || p.type || 'unknown',
        nullable: !required.has(col),
        default: null, // OpenAPI doesn't expose defaults reliably
        pk,
        fk: fkMatch ? fkMatch[1] : null,
      }
    })
    tables.push({ name, columns })
  }
  return { method: 'postgrest:openapi', tables: tables.sort(byName) }
}

const byName = (a, b) => a.name.localeCompare(b.name)

// ── render markdown catalog ──
function toMarkdown({ method, tables }, stamp) {
  const lines = []
  lines.push('# Supabase schema (public)')
  lines.push('')
  lines.push(`_Snapshot generated by \`npm run db:schema\` on ${stamp} via ${method}._`)
  lines.push(`_${tables.length} tables. Do not edit by hand — re-run the command after migrations._`)
  if (method.startsWith('postgrest')) {
    lines.push('')
    lines.push('> Note: column **defaults** are not captured by this method. Install `sql/2026-06-25_schema_catalog_rpc.sql` and re-run for full fidelity (exact types + defaults).')
  }
  lines.push('')
  for (const t of tables) {
    lines.push(`## \`${t.name}\``)
    lines.push('')
    lines.push('| Column | Type | Null | Default | Key |')
    lines.push('|---|---|---|---|---|')
    for (const c of t.columns) {
      const key = c.pk ? 'PK' : c.fk ? `FK → ${c.fk}` : ''
      lines.push(`| ${c.name} | ${c.type} | ${c.nullable ? 'yes' : 'no'} | ${c.default ?? ''} | ${key} |`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

;(async () => {
  let result = null
  try { result = await viaRpc() } catch { /* ignore, fall back */ }
  if (result) console.log('✓ Introspected via schema_catalog RPC (full fidelity).')
  else {
    result = await viaOpenApi()
    console.log('✓ Introspected via PostgREST OpenAPI (zero-setup). Install the RPC for defaults.')
  }

  const stamp = new Date().toISOString().slice(0, 19).replace('T', ' ') + ' UTC'
  mkdirSync(resolve(ROOT, 'db'), { recursive: true })
  writeFileSync(resolve(ROOT, 'db/schema.json'), JSON.stringify({ generatedAt: stamp, ...result }, null, 2) + '\n')
  writeFileSync(resolve(ROOT, 'db/schema.md'), toMarkdown(result, stamp) + '\n')

  const cols = result.tables.reduce((s, t) => s + t.columns.length, 0)
  console.log(`✓ Wrote db/schema.json + db/schema.md — ${result.tables.length} tables, ${cols} columns.`)
})().catch(e => { console.error('✗', e.message); process.exit(1) })
