-- TikTok Ads campaign spend, mirroring client_meta_campaigns.
-- Populated by a future /api/sync-tiktok-ads route (TikTok Marketing API).
-- Non-sensitive spend table → readable by anon (like client_meta_campaigns);
-- the connection/token table (tiktok_connections) stays locked down.

create table if not exists client_tiktok_campaigns (
  id                bigint generated by default as identity primary key,
  client_id         text not null,
  campaign_id       text not null,
  campaign_name     text,
  status            text,
  budget            numeric default 0,
  spend             numeric default 0,
  impressions       numeric default 0,
  clicks            numeric default 0,
  conversions       numeric default 0,
  conversions_value numeric default 0,
  date              date not null,
  synced_at         timestamptz default now(),
  unique (client_id, campaign_id, date)
);

create index if not exists idx_tiktok_campaigns_client_date
  on client_tiktok_campaigns (client_id, date);

-- Same access posture as the Meta spend table: spend is non-sensitive.
alter table client_tiktok_campaigns disable row level security;
grant select on client_tiktok_campaigns to anon, authenticated;

-- Connection/credentials table (advertiser id + access token) — locked down,
-- service-role only, never exposed to the browser.
create table if not exists tiktok_connections (
  client_id      text primary key,
  advertiser_id  text,
  access_token    text,
  app_secret     text,
  created_at     timestamptz default now()
);
alter table tiktok_connections enable row level security;
